swagger: "2.0"

info:
  version: 1.0.0
  title: Room Service API
  description: A description of the Room Service API using OpenAPI Specification.

schemes:
  - http

#host: www.example.com
#basePath: /

paths:
  /rooms:
    get:
      summary: Retrieves a list of rooms.
      produces:
        - "application/json"
      parameters:
        - name: "user"
          in: query
          description: The username of the user which made the request.
          required: true
          type: "string"
      responses:
        200:
          description: A list of Room
          schema:
            type: array
            items:
              required:
                - name
              properties:
                name:
                  type: string
    post:
      summary: Creates a new room.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: room
          in: body
          description: The room to create.
          schema:
            required:
              - name
              - username
            properties:
              name:
                type: string
              username:
                type: string
          required: true
      responses:
        201:
          description: The room was successfully created.
          schema:
            required:
              - name
            properties:
              name:
                type: string
  /rooms/{name}:
    delete:
      summary: Deletes a room.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room to delete.
          required: true
          type: "string"
        - name: room
          in: body
          description: The room to delete.
          schema:
            required:
              - username
            properties:
              username:
                type: string
          required: true
      responses:
        200:
          description: The room was successfully deleted.
          schema:
            required:
              - name
            properties:
              name:
                type: string
  /rooms/{name}/participations:
    get:
      summary: Retrieves all the participations for a given room.
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room.
          required: true
          type: "string"
      responses:
        200:
          description: A list of all the participations for the given room.
          schema:
            type: array
            items:
              required:
                - user
              properties:
                user:
                  required:
                    - username
                  properties:
                    username:
                      type: string
    post:
      summary: Creates a new participation.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room to in which create the participation.
          required: true
          type: "string"
        - name: user
          in: body
          description: The user that joins the room.
          schema:
            required:
              - username
            properties:
              username:
                type: string
          required: true
      responses:
        201:
          description: The participation was successfully created.
          schema:
            required:
              - room
              - username
              - joinDate
            properties:
              room:
                required:
                  - name
                properties:
                  name:
                    type: string
              username:
                type: string
              joinDate:
                type: string
                format: date-time
  /rooms/{name}/participations/{username}:
    delete:
      summary: Deletes a participation.
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room in which to delete the participation.
          required: true
          type: "string"
        - name: "username"
          in: path
          description: The username of the user for which to delete the participation.
          required: true
          type: "string"
      responses:
        204:
          description: The participation was successfully deleted.
          schema:
            required:
              - name
              - username
            properties:
              name:
                type: string
              username:
                type: string

  /rooms/{name}/messages:
    get:
      summary: Retrieves a list of all the messages in a room.
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room in which retrieve the messages.
          required: true
          type: "string"
      responses:
        200:
          description: A list of Message
          schema:
            type: array
            items:
              required:
                - content
                - timestamp
                - participation
              properties:
                content:
                  type: string
                participation:
                  required:
                    - room
                    - username
                  properties:
                    room:
                      required:
                        - name
                      properties:
                        name:
                          type: string
                    username:
                      type: string
                timestamp:
                  type: string
                  format: date-time
    post:
      summary: Creates a new message in a room.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room in which retrieve the messages.
          required: true
          type: "string"
        - name: message
          in: body
          description: The Message to create.
          schema:
            required:
              - content
              - username
            properties:
              content:
                type: string
              username:
                type: string
          required: true
      responses:
        201:
          description: The message was successfully created.
          schema:
              required:
                - content
                - timestamp
                - participation
              properties:
                content:
                  type: string
                participation:
                  required:
                    - room
                    - username
                  properties:
                    room:
                      required:
                        - name
                      properties:
                        name:
                          type: string
                    username:
                      type: string
                timestamp:
                  type: string
                  format: date-time

  /users:
    post:
      summary: Creates a new User.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: user
          in: body
          description: The user to create.
          schema:
            required:
              - username
            properties:
              username:
                type: string
          required: true
      responses:
        201:
          description: The user was successfully created.
  /users/{username}:
    delete:
      summary: Deletes a User.
      produces:
        - "application/json"
      parameters:
        - name: "username"
          in: path
          description: The username of the user to delete.
          required: true
          type: "string"
      responses:
        204:
          description: The user was successfully deleted.

  /users/{username}/participations:
    get:
      summary: Retrieves all the participations for a given user.
      produces:
        - "application/json"
      parameters:
        - name: "username"
          in: path
          description: The username of the user.
          required: true
          type: "string"
      responses:
        200:
          description: A list of all the user's participations.
          schema:
            type: array
            items:
              required:
                - room
              properties:
                room:
                  required:
                    - name
                  properties:
                    name:
                      type: string
